[package]
name = "holochain-collections"
version = "0.1.1"
authors = ["willem <willemolding@gmail.com>"]
edition = "2018"

[dependencies]
hdk = { git = "https://github.com/holochain/holochain-rust" , tag = "v0.0.49-alpha1" }
multihash = "0.8.0"
bs58 = "=0.3.1"

[workspace]
exclude = ["examples"]
