[package]
name = "holochain-collections"
version = "0.1.2"
authors = ["willem <willemolding@gmail.com>"]
edition = "2018"

[dependencies]
hdk = "=0.0.50-alpha4"
multihash = "0.8.0"
bs58 = "=0.3.1"

[workspace]
exclude = ["examples"]
